apiVersion: v2
name: traefik-ingress
version: 1.1.10
kubeVersion: ">= 1.16.0-0"
appVersion: 2.4.11
description: "A Kubernetes Ingress Controller based on Traefik"
type: application
keywords:
  - traefik
  - ingress
home: https://github.com/mia-platform/helm-charts
sources:
  - https://github.com/containous/traefik
maintainers:
  - name: "Jacopo Andrea Giola"
    url: https://github.com/JGiola
  - name: "Thomas Bianchi"
    url: https://github.com/thobianchi
  - name: "Luca Terracciano"
    url: https://github.com/lterrac
icon: https://docs.traefik.io/assets/img/traefik.logo.png
deprecated: false
