remote: "origin"
target-branch: "main"
lint-conf: "./lint/lintconf.yaml"
chart-yaml-schema: "./lint/chart_schema.yaml"
validate-maintainers: false
validate-chart-schema: true
validate-yaml: true
check-version-increment: false
chart-dirs:
  - "charts/traefik-ingress"
debug: true
helm-extra-args: -f lint/traefik-test-values.yaml
