apiVersion: v2
name: logging-operator
version: 3.6.1
kubeVersion: ">= 1.16.0-0"
appVersion: 3.15.0
description: "A Kubernetes logging stack based on Logging Operator"
type: application
keywords:
  - logging
  - logging-operator
  - fluentd
  - fluent-bit
home: https://github.com/mia-platform/helm-charts
sources:
  - https://github.com/banzaicloud/logging-operator
maintainers:
  - name: "Jacopo Andrea Giola"
    url: https://github.com/JGiola
  - name: "Thomas Bianchi"
    url: https://github.com/thobianchi
  - name: "Luca Terracciano"
    url: https://github.com/lterrac
icon: https://github.com/banzaicloud/logging-operator/blob/master/docs/img/icon.png
deprecated: false
