{{- /*
This rules are lifted from the 'kubernetes-apps' group from https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/kubernetes-prometheusRule.yaml
We only divide the list in sub resources for better skimming through them
*/ -}}
{{- $kubeStateMetricsJob := printf "%s" (include "mia-monitoring.kubeStateMetrics.name" .) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-kubernetes-apps" .Release.Name | quote }}
  labels:
    {{- include "mia-monitoring.labels" . | nindent 4 }}
  {{- with .Values.deploy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
    - name: kubernetes-apps
      rules:
        - alert: "KubePodCrashLooping"
          annotations:
            description: "Pod {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod {{`}}`}} ({{`{{`}} $labels.container {{`}}`}}) is in waiting state (reason: \"CrashLoopBackOff\")."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping"
            summary: "Pod is crash looping."
          expr: |
            max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", job="{{ $kubeStateMetricsJob }}"}[5m]) >= 1
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubePodNotReady"
          annotations:
            description: "Pod {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod {{`}}`}} has been in a non-ready state for longer than 15 minutes."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready"
            summary: "Pod has been in a non-ready state for more than 15 minutes."
          expr: |
            sum by (namespace, pod) (
              max by(namespace, pod) (
                kube_pod_status_phase{job="{{ $kubeStateMetricsJob }}", phase=~"Pending|Unknown"}
              ) * on(namespace, pod) group_left(owner_kind) topk by(namespace, pod) (
                1, max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"})
              )
            ) > 0
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeDeploymentGenerationMismatch"
          annotations:
            description: "Deployment generation for {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.deployment {{`}}`}} does not match, this indicates that the Deployment has failed but has not been rolled back."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch"
            summary: "Deployment generation mismatch due to possible roll-back"
          expr: |
            kube_deployment_status_observed_generation{job="{{ $kubeStateMetricsJob }}"}
              !=
            kube_deployment_metadata_generation{job="{{ $kubeStateMetricsJob }}"}
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeDeploymentReplicasMismatch"
          annotations:
            description: "Deployment {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.deployment {{`}}`}} has not matched the expected number of replicas for longer than 15 minutes."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentreplicasmismatch"
            summary: "Deployment has not matched the expected number of replicas."
          expr: |
            (
              kube_deployment_spec_replicas{job="{{ $kubeStateMetricsJob }}"}
                >
              kube_deployment_status_replicas_available{job="{{ $kubeStateMetricsJob }}"}
            ) and (
              changes(kube_deployment_status_replicas_updated{job="{{ $kubeStateMetricsJob }}"}[10m])
                ==
              0
            )
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeStatefulSetReplicasMismatch"
          annotations:
            description: "StatefulSet {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.statefulset {{`}}`}} has not matched the expected number of replicas for longer than 15 minutes."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetreplicasmismatch"
            summary: "Deployment has not matched the expected number of replicas."
          expr: |
            (
              kube_statefulset_status_replicas_ready{job="{{ $kubeStateMetricsJob }}"}
                !=
              kube_statefulset_status_replicas{job="{{ $kubeStateMetricsJob }}"}
            ) and (
              changes(kube_statefulset_status_replicas_updated{job="{{ $kubeStateMetricsJob }}"}[10m])
                ==
              0
            )
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeStatefulSetGenerationMismatch"
          annotations:
            description: "StatefulSet generation for {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.statefulset {{`}}`}} does not match, this indicates that the StatefulSet has failed but has not been rolled back."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetgenerationmismatch"
            summary: "StatefulSet generation mismatch due to possible roll-back"
          expr: |
            kube_statefulset_status_observed_generation{job="{{ $kubeStateMetricsJob }}"}
              !=
            kube_statefulset_metadata_generation{job="{{ $kubeStateMetricsJob }}"}
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeStatefulSetUpdateNotRolledOut"
          annotations:
            description: "StatefulSet {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.statefulset {{`}}`}} update has not been rolled out."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetupdatenotrolledout"
            summary: "StatefulSet update has not been rolled out."
          expr: |
            (
              max without (revision) (
                kube_statefulset_status_current_revision{job="{{ $kubeStateMetricsJob }}"}
                  unless
                kube_statefulset_status_update_revision{job="{{ $kubeStateMetricsJob }}"}
              )
                *
              (
                kube_statefulset_replicas{job="{{ $kubeStateMetricsJob }}"}
                  !=
                kube_statefulset_status_replicas_updated{job="{{ $kubeStateMetricsJob }}"}
              )
            )  and (
              changes(kube_statefulset_status_replicas_updated{job="{{ $kubeStateMetricsJob }}"}[5m])
                ==
              0
            )
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeDaemonSetRolloutStuck"
          annotations:
            description: "DaemonSet {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.daemonset {{`}}`}} has not finished or progressed for at least 15 minutes."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck"
            summary: "DaemonSet rollout is stuck."
          expr: |
            (
              (
                kube_daemonset_status_current_number_scheduled{job="{{ $kubeStateMetricsJob }}"}
                !=
                kube_daemonset_status_desired_number_scheduled{job="{{ $kubeStateMetricsJob }}"}
              ) or (
                kube_daemonset_status_number_misscheduled{job="{{ $kubeStateMetricsJob }}"}
                !=
                0
              ) or (
                kube_daemonset_updated_number_scheduled{job="{{ $kubeStateMetricsJob }}"}
                !=
                kube_daemonset_status_desired_number_scheduled{job="{{ $kubeStateMetricsJob }}"}
              ) or (
                kube_daemonset_status_number_available{job="{{ $kubeStateMetricsJob }}"}
                !=
                kube_daemonset_status_desired_number_scheduled{job="{{ $kubeStateMetricsJob }}"}
              )
            ) and (
              changes(kube_daemonset_updated_number_scheduled{job="{{ $kubeStateMetricsJob }}"}[5m])
                ==
              0
            )
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeContainerWaiting"
          annotations:
            description: "Pod {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod {{`}}`}} container {{`{{`}} $labels.container{{`}}`}} has been in waiting state for longer than 1 hour."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontainerwaiting"
            summary: "Pod container waiting longer than 1 hour"
          expr: |
            sum by (namespace, pod, container) (kube_pod_container_status_waiting_reason{job="{{ $kubeStateMetricsJob }}"}) > 0
          for: "1h"
          labels:
            severity: "warning"
        - alert: "KubeDaemonSetNotScheduled"
          annotations:
            description: "{{`{{`}} $value {{`}}`}} Pods of DaemonSet {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.daemonset {{`}}`}} are not scheduled."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetnotscheduled"
            summary: "DaemonSet pods are not scheduled."
          expr: |
            kube_daemonset_status_desired_number_scheduled{job="{{ $kubeStateMetricsJob }}"}
              -
            kube_daemonset_status_current_number_scheduled{job="{{ $kubeStateMetricsJob }}"} > 0
          for: "10m"
          labels:
            severity: "warning"
        - alert: "KubeDaemonSetMisScheduled"
          annotations:
            description: "{{`{{`}} $value {{`}}`}} Pods of DaemonSet {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.daemonset {{`}}`}} are running where they are not supposed to run."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetmisscheduled"
            summary: "DaemonSet pods are misscheduled."
          expr: |
            kube_daemonset_status_number_misscheduled{job="{{ $kubeStateMetricsJob }}"} > 0
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeJobCompletion"
          annotations:
            description: "Job {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.job_name {{`}}`}} is taking more than 12 hours to complete."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobcompletion"
            summary: "Job did not complete in time"
          expr: |
            kube_job_spec_completions{job="{{ $kubeStateMetricsJob }}"} - kube_job_status_succeeded{job="{{ $kubeStateMetricsJob }}"}  > 0
          for: "12h"
          labels:
            severity: "warning"
        - alert: "KubeJobFailed"
          annotations:
            description: "Job {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.job_name {{`}}`}} failed to complete. Removing failed job after investigation should clear this alert."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobfailed"
            summary: "Job failed to complete."
          expr: |
            kube_job_failed{job="{{ $kubeStateMetricsJob }}"}  > 0
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeHpaReplicasMismatch"
          annotations:
            description: "HPA {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.horizontalpodautoscaler  {{`}}`}} has not matched the desired number of replicas for longer than 15 minutes."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubehpareplicasmismatch"
            summary: "HPA has not matched descired number of replicas."
          expr: |
            (kube_horizontalpodautoscaler_status_desired_replicas{job="{{ $kubeStateMetricsJob }}"}
              !=
            kube_horizontalpodautoscaler_status_current_replicas{job="{{ $kubeStateMetricsJob }}"})
              and
            (kube_horizontalpodautoscaler_status_current_replicas{job="{{ $kubeStateMetricsJob }}"}
              >
            kube_horizontalpodautoscaler_spec_min_replicas{job="{{ $kubeStateMetricsJob }}"})
              and
            (kube_horizontalpodautoscaler_status_current_replicas{job="{{ $kubeStateMetricsJob }}"}
              <
            kube_horizontalpodautoscaler_spec_max_replicas{job="{{ $kubeStateMetricsJob }}"})
              and
            changes(kube_horizontalpodautoscaler_status_current_replicas{job="{{ $kubeStateMetricsJob }}"}[15m]) == 0
          for: "15m"
          labels:
            severity: "warning"
        - alert: "KubeHpaMaxedOut"
          annotations:
            description: "HPA {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.horizontalpodautoscaler  {{`}}`}} has been running at max replicas for longer than 15 minutes."
            runbook_url: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubehpamaxedout"
            summary: "HPA is running at max replicas"
          expr: |
            kube_horizontalpodautoscaler_status_current_replicas{job="{{ $kubeStateMetricsJob }}"}
              ==
            kube_horizontalpodautoscaler_spec_max_replicas{job="{{ $kubeStateMetricsJob }}"}
          for: "15m"
          labels:
            severity: "warning"
